<?php $Cards = array (
  'card0' => 
  array (
    'name' => 'Pikachu',
    'type' => 'electric',
    'hp' => 60,
    'attack' => 20,
    'defense' => 20,
    'price' => 160,
    'description' => 'Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
    'owner' => 'qweq',
  ),
  'card1' => 
  array (
    'name' => 'Charizard',
    'type' => 'fire',
    'hp' => 78,
    'attack' => 84,
    'defense' => 78,
    'price' => 534,
    'description' => 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    'owner' => 'asd',
  ),
  'card2' => 
  array (
    'name' => 'Bulbasaur',
    'type' => 'grass',
    'hp' => 45,
    'attack' => 49,
    'defense' => 49,
    'price' => 318,
    'description' => 'A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    'owner' => 'asd',
  ),
  'card3' => 
  array (
    'name' => 'Squirtle',
    'type' => 'water',
    'hp' => 44,
    'attack' => 48,
    'defense' => 65,
    'price' => 314,
    'description' => 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    'owner' => 'asd',
  ),
  'card4' => 
  array (
    'name' => 'Caterpie',
    'type' => 'bug',
    'hp' => 45,
    'attack' => 30,
    'defense' => 35,
    'price' => 195,
    'description' => 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    'owner' => 'admin',
  ),
  'card5' => 
  array (
    'name' => 'Weedle',
    'type' => 'bug',
    'hp' => 40,
    'attack' => 35,
    'defense' => 30,
    'price' => 195,
    'description' => 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    'owner' => 'admin',
  ),
  'card6' => 
  array (
    'name' => 'Pidgey',
    'type' => 'normal',
    'hp' => 40,
    'attack' => 45,
    'defense' => 40,
    'price' => 251,
    'description' => 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png',
    'owner' => 'admin',
  ),
  'card7' => 
  array (
    'name' => 'Rattata',
    'type' => 'normal',
    'hp' => 30,
    'attack' => 56,
    'defense' => 35,
    'price' => 253,
    'description' => 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png',
    'owner' => 'admin',
  ),
  'card8' => 
  array (
    'name' => 'Spearow',
    'type' => 'normal',
    'hp' => 40,
    'attack' => 60,
    'defense' => 30,
    'price' => 262,
    'description' => 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png',
    'owner' => 'admin',
  ),
  'card9' => 
  array (
    'name' => 'Ekans',
    'type' => 'poison',
    'hp' => 35,
    'attack' => 60,
    'defense' => 44,
    'price' => 288,
    'description' => 'Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',
    'owner' => 'admin',
  ),
  'card10' => 
  array (
    'name' => 'Pawmot',
    'type' => 'electric',
    'hp' => 130,
    'attack' => 230,
    'defense' => 50,
    'price' => 499,
    'description' => 'Hi I\'m Pawmot!',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/cards/web/SVP/SVP_EN_6.png',
    'owner' => 'admin',
  ),
  'card11' => 
  array (
    'name' => 'Jolteon',
    'type' => 'electric',
    'hp' => 150,
    'attack' => 200,
    'defense' => 60,
    'price' => 600,
    'description' => 'Hi i\'m Jolteon!',
    'image' => 'https://assets.pokemon.com/assets/cms2/img/cards/web/BWP/BWP_EN_BW91.png',
    'owner' => 'admin',
  ),
);